name: ci-build

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # checkout the code
      - name: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # setup dotnet based on global.json
      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
      # build it, test it, pack it
      - name: Run dotnet build (release)
        # see issue #105
        # very important, since we use cmd scripts, the default is psh, and a bug prevents errorlevel to bubble
        shell: cmd
        run: ./build.cmd
