name: ci-build

on: [pull_request]

jobs:
  verify_formatting:
    runs-on: ubuntu-latest
    name: Verify code formatting

    steps:
      - name: checkout-code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup-dotnet
        uses: actions/setup-dotnet@v4
  
      - name: tool restore
        run: dotnet tool restore
  
      - name: validate formatting
        run: dotnet fantomas . --check

  build:
    name: Build
    runs-on: windows-latest
    steps:
      # checkout the code
      - name: checkout-code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # setup dotnet based on global.json
      - name: setup-dotnet
        uses: actions/setup-dotnet@v4

      # build it, test it, pack it
      - name: Run dotnet build (release)
        # see issue #105
        # very important, since we use cmd scripts, the default is psh, and a bug prevents errorlevel to bubble
        shell: cmd
        run: ./build.cmd
