name: ci-test

on: [pull_request]

jobs:
  test-release:
    name: Test Release Build
    runs-on: windows-latest
    steps:
      # checkout the code
      - name: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # setup dotnet based on global.json
      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
      # build it, test it
      - name: Run dotnet test - release
        run: ./build.cmd ci -release
      - name: Publish test results - release
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Report release tests
          # this path glob pattern requires forward slashes!
          path: ./src/FSharp.Control.TaskSeq.Test/TestResults/test-results-release.trx
          reporter: dotnet-trx

  test-debug:
    name: Test Debug Build
    runs-on: windows-latest
    steps:
      # checkout the code
      - name: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # setup dotnet based on global.json
      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
      # build it, test it
      - name: Run dotnet test - debug
        run: ./build.cmd ci -debug
      - name: Publish test results - debug
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Report debug tests
          # this path glob pattern requires forward slashes!
          path: ./src/FSharp.Control.TaskSeq.Test/TestResults/test-results-debug.trx
          reporter: dotnet-trx
